-- DartsScheduler v7: čista instalacija za novi Supabase projekt.
-- Ne pokretati na postojećoj DartsScheduler bazi; za nju koristite upgrade_v7_organizations.sql.
begin;
create extension if not exists pgcrypto;

create table public.organizations(id uuid primary key default gen_random_uuid(),name text not null,slug text not null unique,country_code text not null default 'HR',default_language text not null default 'en',website text not null default '',logo_url text not null default '',is_active boolean not null default true,created_at timestamptz not null default now());
create table public.seasons(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,is_active boolean not null default false,created_at timestamptz not null default now(),unique(organization_id,name));
create table public.venues(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,address text not null default '',is_featured boolean not null default false,contact_name text not null default '',phone text not null default '',email text not null default '',map_url text not null default '',note text not null default '',created_at timestamptz not null default now(),unique(organization_id,name));
create table public.clubs(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,contact_name text not null default '',phone text not null default '',email text not null default '',note text not null default '',created_at timestamptz not null default now(),unique(organization_id,name));
create table public.teams(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,name text not null,club_id uuid references public.clubs(id) on delete set null,club_name text not null default '',default_venue_id uuid references public.venues(id) on delete set null,contact_name text not null default '',phone text not null default '',email text not null default '',note text not null default '',created_at timestamptz not null default now(),unique(organization_id,name));
create table public.competitions(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,season_id uuid not null references public.seasons(id) on delete cascade,name text not null,external_id text not null default '',created_at timestamptz not null default now(),unique(season_id,name),unique(season_id,external_id));
create table public.competition_teams(competition_id uuid not null references public.competitions(id) on delete cascade,team_id uuid not null references public.teams(id) on delete cascade,primary key(competition_id,team_id));
create table public.matches(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,match_date date not null,match_time time,home_team_id uuid not null references public.teams(id) on delete cascade,away_team_id uuid not null references public.teams(id) on delete cascade,venue_id uuid references public.venues(id) on delete set null,competition_id uuid references public.competitions(id) on delete set null,external_event_id text not null default '',league text not null default '',round_name text not null default '',note text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(home_team_id<>away_team_id));
create unique index matches_competition_event_uq on public.matches(competition_id,external_event_id) where external_event_id<>'';
create index matches_org_date_idx on public.matches(organization_id,match_date);
create table public.app_users(email text primary key,user_id uuid unique references auth.users(id) on delete set null,role text not null check(role in('platform_admin','organization_admin','club_manager','captain')),created_by uuid references auth.users(id) on delete set null,created_at timestamptz not null default now());
create table public.organization_admins(organization_id uuid not null references public.organizations(id) on delete cascade,email text not null references public.app_users(email) on delete cascade,created_at timestamptz not null default now(),primary key(organization_id,email));
create table public.club_venues(club_id uuid not null references public.clubs(id) on delete cascade,venue_id uuid not null references public.venues(id) on delete cascade,primary key(club_id,venue_id));
create table public.club_managers(club_id uuid not null references public.clubs(id) on delete cascade,email text not null references public.app_users(email) on delete cascade,created_at timestamptz not null default now(),primary key(club_id,email));
create table public.team_editors(team_id uuid not null references public.teams(id) on delete cascade,email text not null references public.app_users(email) on delete cascade,created_at timestamptz not null default now(),primary key(team_id,email));
create table public.schedule_changes(id uuid primary key default gen_random_uuid(),match_id uuid not null references public.matches(id) on delete cascade,organization_id uuid not null references public.organizations(id) on delete cascade,changed_at timestamptz not null default now(),changed_by text not null default '',old_date date,new_date date,old_time time,new_time time,old_venue_id uuid references public.venues(id) on delete set null,new_venue_id uuid references public.venues(id) on delete set null);
create table public.venue_bookings(id uuid primary key default gen_random_uuid(),organization_id uuid not null references public.organizations(id) on delete cascade,venue_id uuid not null references public.venues(id) on delete cascade,event_date date not null,start_time time,end_time time,title text not null,organizer text not null default '',note text not null default '',created_by text not null default '',created_at timestamptz not null default now(),updated_at timestamptz not null default now(),check(end_time is null or start_time is null or end_time>start_time));

create or replace function public.is_platform_admin() returns boolean language sql stable security definer set search_path='' as $$select exists(select 1 from public.app_users where role='platform_admin' and(user_id=auth.uid() or lower(email)=lower(coalesce(auth.jwt()->>'email',''))))$$;
create or replace function public.is_organization_admin(target uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_platform_admin() or exists(select 1 from public.organization_admins where organization_id=target and lower(email)=lower(coalesce(auth.jwt()->>'email','')))$$;
create or replace function public.is_any_organization_admin() returns boolean language sql stable security definer set search_path='' as $$select public.is_platform_admin() or exists(select 1 from public.organization_admins where lower(email)=lower(coalesce(auth.jwt()->>'email','')))$$;
create or replace function public.is_admin() returns boolean language sql stable security definer set search_path='' as $$select public.is_platform_admin()$$;
create or replace function public.current_app_role() returns text language sql stable security definer set search_path='' as $$select case when public.is_platform_admin() then 'platform_admin' when public.is_any_organization_admin() then 'organization_admin' when exists(select 1 from public.club_managers where lower(email)=lower(coalesce(auth.jwt()->>'email',''))) then 'club_manager' when exists(select 1 from public.team_editors where lower(email)=lower(coalesce(auth.jwt()->>'email',''))) then 'captain' else 'viewer' end$$;
create or replace function public.current_organization_role(target uuid) returns text language sql stable security definer set search_path='' as $$select case when public.is_platform_admin() then 'platform_admin' when public.is_organization_admin(target) then 'organization_admin' when exists(select 1 from public.club_managers cm join public.clubs c on c.id=cm.club_id where c.organization_id=target and lower(cm.email)=lower(coalesce(auth.jwt()->>'email',''))) then 'club_manager' when exists(select 1 from public.team_editors te join public.teams t on t.id=te.team_id where t.organization_id=target and lower(te.email)=lower(coalesce(auth.jwt()->>'email',''))) then 'captain' else 'viewer' end$$;
create or replace function public.can_manage_club(target uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_organization_admin((select organization_id from public.clubs where id=target)) or exists(select 1 from public.club_managers where club_id=target and lower(email)=lower(coalesce(auth.jwt()->>'email','')))$$;
create or replace function public.can_edit_team(target uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_organization_admin((select organization_id from public.teams where id=target)) or exists(select 1 from public.team_editors where team_id=target and lower(email)=lower(coalesce(auth.jwt()->>'email',''))) or exists(select 1 from public.teams t join public.club_managers cm on cm.club_id=t.club_id where t.id=target and lower(cm.email)=lower(coalesce(auth.jwt()->>'email','')))$$;
create or replace function public.can_edit_venue(target uuid) returns boolean language sql stable security definer set search_path='' as $$select public.is_organization_admin((select organization_id from public.venues where id=target)) or exists(select 1 from public.club_venues cv join public.club_managers cm on cm.club_id=cv.club_id where cv.venue_id=target and lower(cm.email)=lower(coalesce(auth.jwt()->>'email','')))$$;
create or replace function public.can_edit_match(home_id uuid,away_id uuid) returns boolean language sql stable security definer set search_path='' as $$select public.can_edit_team(home_id) or public.can_edit_team(away_id)$$;
create or replace function public.link_invited_app_user() returns trigger language plpgsql security definer set search_path='' as $$begin update public.app_users set user_id=new.id where lower(email)=lower(new.email);return new;end$$;
create trigger link_invited_app_user after insert or update of email,last_sign_in_at on auth.users for each row execute function public.link_invited_app_user();
create or replace function public.limit_team_editors() returns trigger language plpgsql security definer set search_path='' as $$begin if(select count(*) from public.team_editors where team_id=new.team_id)>=2 then raise exception 'Team already has two captains.';end if;return new;end$$;
create trigger limit_team_editors before insert on public.team_editors for each row execute function public.limit_team_editors();
create or replace function public.protect_last_organization_admin() returns trigger language plpgsql security definer set search_path='' as $$begin if(select count(*) from public.organization_admins where organization_id=old.organization_id)<=1 then raise exception 'An organization must retain one administrator.';end if;return old;end$$;
create trigger protect_last_organization_admin before delete on public.organization_admins for each row execute function public.protect_last_organization_admin();
create or replace function public.log_schedule_change() returns trigger language plpgsql security definer set search_path='' as $$begin if old.match_date is distinct from new.match_date or old.match_time is distinct from new.match_time or old.venue_id is distinct from new.venue_id then insert into public.schedule_changes(match_id,organization_id,changed_by,old_date,new_date,old_time,new_time,old_venue_id,new_venue_id) values(new.id,new.organization_id,coalesce(auth.jwt()->>'email','administrator'),old.match_date,new.match_date,old.match_time,new.match_time,old.venue_id,new.venue_id);end if;new.updated_at=now();return new;end$$;
create trigger log_schedule_change before update on public.matches for each row execute function public.log_schedule_change();

alter table public.organizations enable row level security;alter table public.seasons enable row level security;alter table public.competitions enable row level security;alter table public.venues enable row level security;alter table public.clubs enable row level security;alter table public.teams enable row level security;alter table public.matches enable row level security;alter table public.competition_teams enable row level security;alter table public.app_users enable row level security;alter table public.organization_admins enable row level security;alter table public.club_venues enable row level security;alter table public.club_managers enable row level security;alter table public.team_editors enable row level security;alter table public.schedule_changes enable row level security;alter table public.venue_bookings enable row level security;
grant select on public.organizations,public.seasons,public.competitions,public.venues,public.clubs,public.teams,public.matches,public.competition_teams,public.club_venues,public.schedule_changes,public.venue_bookings to anon,authenticated;
grant insert,update,delete on public.organizations,public.seasons,public.competitions,public.venues,public.clubs,public.teams,public.matches,public.competition_teams,public.club_venues,public.venue_bookings to authenticated;
grant select,insert,update,delete on public.app_users,public.organization_admins,public.club_managers,public.team_editors to authenticated;
grant execute on function public.is_platform_admin(),public.is_organization_admin(uuid),public.is_any_organization_admin(),public.current_app_role(),public.current_organization_role(uuid),public.can_manage_club(uuid),public.can_edit_team(uuid),public.can_edit_venue(uuid),public.can_edit_match(uuid,uuid) to authenticated;

create policy "public organizations" on public.organizations for select using(true);create policy "platform insert organizations" on public.organizations for insert to authenticated with check(public.is_platform_admin());create policy "admins update organizations" on public.organizations for update to authenticated using(public.is_organization_admin(id)) with check(public.is_organization_admin(id));create policy "platform delete organizations" on public.organizations for delete to authenticated using(public.is_platform_admin());
create policy "public seasons" on public.seasons for select using(true);create policy "admins seasons" on public.seasons for all to authenticated using(public.is_organization_admin(organization_id)) with check(public.is_organization_admin(organization_id));
create policy "public competitions" on public.competitions for select using(true);create policy "admins competitions" on public.competitions for all to authenticated using(public.is_organization_admin(organization_id)) with check(public.is_organization_admin(organization_id));
create policy "public venues" on public.venues for select using(true);create policy "admins insert venues" on public.venues for insert to authenticated with check(public.is_organization_admin(organization_id));create policy "authorized update venues" on public.venues for update to authenticated using(public.can_edit_venue(id)) with check(public.can_edit_venue(id));create policy "admins delete venues" on public.venues for delete to authenticated using(public.is_organization_admin(organization_id));
create policy "public clubs" on public.clubs for select using(true);create policy "admins insert clubs" on public.clubs for insert to authenticated with check(public.is_organization_admin(organization_id));create policy "authorized update clubs" on public.clubs for update to authenticated using(public.can_manage_club(id)) with check(public.can_manage_club(id));create policy "admins delete clubs" on public.clubs for delete to authenticated using(public.is_organization_admin(organization_id));
create policy "public teams" on public.teams for select using(true);create policy "admins insert teams" on public.teams for insert to authenticated with check(public.is_organization_admin(organization_id));create policy "authorized update teams" on public.teams for update to authenticated using(public.can_edit_team(id)) with check(public.can_edit_team(id));create policy "admins delete teams" on public.teams for delete to authenticated using(public.is_organization_admin(organization_id));
create policy "public matches" on public.matches for select using(true);create policy "authorized insert matches" on public.matches for insert to authenticated with check(public.can_edit_match(home_team_id,away_team_id));create policy "authorized update matches" on public.matches for update to authenticated using(public.can_edit_match(home_team_id,away_team_id)) with check(public.can_edit_match(home_team_id,away_team_id));create policy "admins delete matches" on public.matches for delete to authenticated using(public.is_organization_admin(organization_id));
create policy "public memberships" on public.competition_teams for select using(true);create policy "admins memberships" on public.competition_teams for all to authenticated using(public.is_organization_admin((select organization_id from public.competitions where id=competition_id))) with check(public.is_organization_admin((select organization_id from public.competitions where id=competition_id)));
create policy "public club venues" on public.club_venues for select using(true);create policy "admins club venues" on public.club_venues for all to authenticated using(public.is_organization_admin((select organization_id from public.clubs where id=club_id))) with check(public.is_organization_admin((select organization_id from public.clubs where id=club_id)));
create policy "own app user" on public.app_users for select to authenticated using(lower(email)=lower(coalesce(auth.jwt()->>'email','')) or public.is_platform_admin() or public.is_any_organization_admin());create policy "admins app users" on public.app_users for all to authenticated using(public.is_platform_admin() or public.is_any_organization_admin()) with check(public.is_platform_admin() or public.is_any_organization_admin());
create policy "organization admins visible" on public.organization_admins for select to authenticated using(public.is_organization_admin(organization_id) or lower(email)=lower(coalesce(auth.jwt()->>'email','')));create policy "organization admins writable" on public.organization_admins for all to authenticated using(public.is_organization_admin(organization_id)) with check(public.is_organization_admin(organization_id));
create policy "club managers visible" on public.club_managers for select to authenticated using(lower(email)=lower(coalesce(auth.jwt()->>'email','')) or public.is_organization_admin((select organization_id from public.clubs where id=club_id)));create policy "club managers writable" on public.club_managers for all to authenticated using(public.is_organization_admin((select organization_id from public.clubs where id=club_id))) with check(public.is_organization_admin((select organization_id from public.clubs where id=club_id)));
create policy "captains visible" on public.team_editors for select to authenticated using(lower(email)=lower(coalesce(auth.jwt()->>'email','')) or public.is_organization_admin((select organization_id from public.teams where id=team_id)));create policy "captains writable" on public.team_editors for all to authenticated using(public.is_organization_admin((select organization_id from public.teams where id=team_id))) with check(public.is_organization_admin((select organization_id from public.teams where id=team_id)));
create policy "public changes" on public.schedule_changes for select using(true);
create policy "public bookings" on public.venue_bookings for select using(true);create policy "authorized insert bookings" on public.venue_bookings for insert to authenticated with check(public.is_organization_admin(organization_id) or public.can_edit_venue(venue_id));create policy "authorized update bookings" on public.venue_bookings for update to authenticated using(public.is_organization_admin(organization_id) or public.can_edit_venue(venue_id)) with check(public.is_organization_admin(organization_id) or public.can_edit_venue(venue_id));create policy "authorized delete bookings" on public.venue_bookings for delete to authenticated using(public.is_organization_admin(organization_id) or public.can_edit_venue(venue_id));
commit;
